### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by liuyangc3** [jmespath/jmespath.terminal#28]
Install command
```bash
pip3 install jmespath-terminal
```

output
```bash
Collecting jmespath-terminal
  Using cached jmespath-terminal-0.2.1.tar.gz (6.3 kB)
  Preparing metadata (setup.py) ... done
Collecting jmespath<=1.0.0,>=0.4.1
  Using cached jmespath-1.0.0-py3-none-any.whl (23 kB)
Requirement already satisfied: Pygments<3.0,>=2.0 in /opt/homebrew/lib/python3.10/site-packages (from jmespath-terminal) (2.14.0)
Collecting urwid==1.2.2
  Using cached urwid-1.2.2.tar.gz (585 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      Traceback (most recent call last):
        File "/opt/homebrew/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
        File "/opt/homebrew/lib/python3.10/site-packages/setuptools/dist.py", line 488, in __init__
          _Distribution.__init__(
        File "/opt/homebrew/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 283, in __init__
          self.finalize_options()
        File "/opt/homebrew/lib/python3.10/site-packages/setuptools/dist.py", line 912, in finalize_options
          ep(self)
        File "/opt/homebrew/lib/python3.10/site-packages/setuptools/dist.py", line 932, in _finalize_setup_keywords
          ep.load()(self, ep.name, value)
        File "/opt/homebrew/lib/python3.10/site-packages/setuptools/dist.py", line 330, in invalid_unless_false
          raise DistutilsSetupError(f"{attr} is invalid.")
      distutils.errors.DistutilsSetupError: use_2to3 is invalid.

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/private/var/folders/j7/m1yn6z2547x5_n_bj4n1s35h0000gn/T/pip-install-6yxv1mso/urwid_7e9d523fb2114174ae37a0fdcdb61f98/setup.py", line 85, in <module>
          setup(**setup_d)
        File "/opt/homebrew/lib/python3.10/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "/opt/homebrew/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 152, in setup
          raise SystemExit("error in {} setup command: {}".format(attrs['name'], msg))
      SystemExit: error in urwid setup command: use_2to3 is invalid.
      error in urwid setup command: use_2to3 is invalid.
      Couldn't build the extension module, trying without it...
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by liuyangc3** [comment]
after many times times retrying, I found that it was able to be install with `setuptools==57.5.0`

```bash
python3.10 -m pip install --upgrade setuptools==57.5.0
```

**Comment by chriscroome** [comment]
See also [this thread](https://github.com/jmespath/jmespath.terminal/issues/19#issuecomment-1156039074).

**Comment by chriscroome** [comment]
The [community fork](https://github.com/jmespath-community/jmespath.terminal) installs with newer versions of `setuptools` and Python (for example [on Debian Bookworm](https://github.com/jmespath-community/jmespath.spec/discussions/155)).
